### ISSUE TITLE
Shouldn't it be called omap?

### ISSUE THREAD

**Issue by NV** [rse/oset#2]
It seems to me that you implemented Map, not a Set.

In ECMAScript, Set has an `add(key)` method:

``` javascript
set = new Set
set.add("one")
set.add("two")
```

Set in ECMAScript doesn't have `set(key, value)` method, Map does.

**Comment by rse** [comment]
Yes, good catch: I've now renamed the old map-style collection to OMap and added my plain set-set collection as the new OSet. The library now provides both OMap and OSet collections. This way is resembles the ECMAScript 6 Set/Map but with the extra functionalities like merge/union/intersection/difference and sort operations.
